#!/usr/bin/python

# Author: Ondrej Tuma <mcbig@zeropage.cz>
# Copyright: This module has been placed in the BSD Licence.

"""
A minimal front end to CommonMarkParser, producing Tiny HTML.
"""

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description
from docutils_tinyhtml import Writer
from recommonmark.parser import CommonMarkParser

description = ('Generates Tiny HTML documents from standalone '
               'MarkDown sources.  ' + default_description)

publish_cmdline(parser=CommonMarkParser(), writer=Writer(), writer_name='html',
                description=description)
